### ISSUE TITLE
Red color control characters aren't being interpreted in Windows Command Prompt

### ISSUE THREAD

**Issue by samuelgrigolato** [danilobellini/dose#13]
See the following image for reference:

![control characters issue](https://cloud.githubusercontent.com/assets/352108/20016808/37e7e8b0-a2a8-11e6-89e3-dd4cb67fd053.PNG)

Note that yellow/cyan control characters are being translated just as expected.

**Comment by danilobellini** [comment]
What's the Windows version? Using `cmd.exe`? The same happens with `powershell.exe`?

Everything reported by that screenshot seem to be messages going to the `STD_OUTPUT_HANDLE`, not `STD_ERROR_HANDLE`, so this issue isn't about mixing these.

If you're using Windows 10, probably that's a Windows bug, as `colorama` simply bypasses the ANSI coloring codes to it.

On any other Windows version, [colorama](https://pypi.python.org/pypi/colorama) replaces the ANSI escape codes by calls to the Windows Console Handles API. If that's the case, this should be seen as a `colorama` bug.

**Comment by samuelgrigolato** [comment]
Turns out it isn't a big problem. I was calling clog _before_ `colorama.init`, which was obviously causing problems on Windows.
